### ISSUE TITLE
Including my co-author in the light sensor work

### ISSUE THREAD

**Issue by lknik** [cure53/browser-sec-whitepaper#1]
Hi,

Congrats on your whitepaper! Reading it with interest.

However, would you be so kind and replace "_This was demonstrated by Olejnik et al._" with "_Olejnik and Janc_", since it's two authors only (e.g. as per [Chicago style](http://libguides.murdoch.edu.au/Chicago/examples) or different references on references)? Thanks!

**Comment by cure53** [comment]
Addressed by the commit above, thanks!
