### ISSUE TITLE
Regarding Reference 326 for HPKP Hostile Pinning

### ISSUE THREAD

**Issue by eganist** [cure53/browser-sec-whitepaper#2]
All,

Congratulations on the report! 

Following up on an out-of-band conversation with Mario: Reference 326 regarding Hostile Pinning is ultimately a pointer--several degrees of separation away--to a conference talk delivered by myself and @buu700 (Ryan Lester), so we're seeking an amendment of Reference 326 to cite the original talk directly ("Bryant Zadegan, Ryan Lester, Abusing Bleeding Edge Web Standards for AppSec Glory, DEF CON 24, 2016-08-06").

Reference URL: https://media.defcon.org/DEF%20CON%2024/DEF%20CON%2024%20presentations/DEFCON-24-Bryant-Zadegan-Ryan-Lester-Abusing-Bleeding-Edge-Web-Standards-For-Appsec-Glory-UPDATED.pdf

Cheers,
-Bryant

**Comment by cure53** [comment]
Thanks, valid point - we will take care soon :)

**Comment by eganist** [comment]
Bugcheck: the URL is cropped to "https://media.defcon.org/DEF%20CON%202...andards-For-Appsec-Glory-UPDATED.pdf" which kills the reference (404 not found). Given that there's plenty of room for a multi-line footnote, can we include the full URL so that the reference is unbroken?

**Comment by cure53** [comment]
Weird issue! Thanks for spotting, should be good now.

Also, wee don't do multiline footnotes :D
