### ISSUE TITLE
Link in reference 23 is broken

### ISSUE THREAD

**Issue by iambrosie** [cure53/browser-sec-whitepaper#3]
Hi all,

Again, great work, thanks! Too bad because no Firefox though :-)
Anyway, while going through the paper I noticed the link in reference #23, page 30, is broken.
I believe a similar issue was reported earlier so the fix should be straightforward.
Maybe it would make sense to have a quick go (preferably scripted?) through all links and see if they work? Just saying. 

Regards!

**Comment by cure53** [comment]
Nice find, fixed :)

**Comment by iambrosie** [comment]
Thanks for the fix. I'm going to close this for now.
