### ISSUE TITLE
"Content Type Forcing" page 73, in IE is not working

### ISSUE THREAD

**Issue by missoum1307** [cure53/browser-sec-whitepaper#5]
the described way for changing Content Type "Content Type Forcing" page 73, in IE is not working?

i get " do you want to  open or save "response" .

**Comment by cure53** [comment]
Try on Windows 7 :)

**Comment by missoum1307** [comment]
the same results , is there any thing should be set up ,? 

the vulnerable endpoints I am testing on : 

' links removed for bug bounty sake '

**Comment by cure53** [comment]
You seem to be missing a ">" in your HTML:

```html
<iframe id=x src="redir.php"></iframe> <script>x.location.reload()</script
```

**Comment by missoum1307** [comment]
thanks a lot , it works now. you can the close the issue as resolved.

**Comment by cure53** [comment]
Cool :)
